language: python
before_install:
  - sudo apt-get install -y libblas3 liblapack3 liblapack-dev libblas-dev
python:
  - 3.7
  - 3.8
  - 3.9
install:
  - pip install coveralls tox-travis
script:
  - tox
after_success:
  - coveralls
