language: python
before_install:
  - sudo apt-get install -y libblas3 liblapack3 liblapack-dev libblas-dev
python:
  - 3.6
  - 3.7
install:
  - pip install coveralls tox-travis
script:
  - tox
after_success:
  - coveralls
